server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://192.168.0.114:1433; DatabaseName=new
    username: sa
    password: ZXCasd,123
  mvc:
    view:
      prefix: /templates/
      suffix: .jsp

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.example.demo.entity
  configuration:
    use-column-label: true
    use-generated-keys: true
